      - name: Build Installer (Inno Setup)
        shell: pwsh
        run: |
          mkdir dist\installer 2>$null

          $lines = @(
            '#define MyAppName "MEXC Bot"',
            "#define MyAppVersion ""$env:GITHUB_RUN_NUMBER""",
            '#define MyAppPublisher "Dali5599"',
            '#define MyAppExeName "MEXC Bot.exe"',
            '',
            '[Setup]',
            'AppId={{A1F4B2F8-3D8A-4C6E-8B3D-FA2F3E8A7A01}',
            'AppName={#MyAppName}',
            'AppVersion={#MyAppVersion}',
            'AppPublisher={#MyAppPublisher}',
            'DefaultDirName={pf}\{#MyAppName}',
            'DefaultGroupName={#MyAppName}',
            'OutputDir=dist\installer',
            'OutputBaseFilename=MEXC_Bot_Setup',
            'Compression=lzma',
            'SolidCompression=yes',
            'WizardStyle=modern',
            'ArchitecturesInstallIn64BitMode=x64',
            'PrivilegesRequired=admin',
            '',
            '[Languages]',
            'Name: "english"; MessagesFile: "compiler:Default.isl"',
            # 'Name: "french";  MessagesFile: "compiler:Languages\French.isl"',  # أعدها لاحقاً إذا احتجت
            # 'Name: "arabic";  MessagesFile: "compiler:Languages\Arabic.isl"',  # هذه سبب الخطأ
            '',
            '[Files]',
            'Source: "dist\MEXC Bot\*"; DestDir: "{app}"; Flags: recursesubdirs ignoreversion',
            '',
            '[Icons]',
            'Name: "{group}\{#MyAppName}";        Filename: "{app}\{#MyAppExeName}"',
            'Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon',
            '',
            '[Tasks]',
            'Name: "desktopicon"; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:"; Flags: unchecked',
            '',
            '[Run]',
            'Filename: "{app}\{#MyAppExeName}"; Flags: nowait postinstall skipifsilent',
            '',
            '[UninstallDelete]',
            'Type: filesandordirs; Name: "{app}\logs"',
            'Type: filesandordirs; Name: "{app}\data"'
          )

          $lines | Set-Content -Path installer.iss -Encoding UTF8
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss
