  name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install --only-binary=:all: pandas==2.2.2 numpy
          pip install -r requirements.txt
          pip install pyinstaller python-dotenv uvicorn fastapi jinja2

      - name: Build EXE (PyInstaller)
        shell: pwsh
        run: |
          pyinstaller --noconfirm --clean --name "MEXC Bot" `
            --hidden-import app `
            --add-data "app.py;." `
            --add-data "templates;templates" `
            --add-data "static;static" `
            --add-data "locales;locales" `
            --add-data "config.yaml;." `
            --add-data ".env.example;." `
            app_launcher.py

      - name: Install Inno Setup
        shell: pwsh
        run: choco install innosetup -y

      - name: Build Installer (Inno Setup)
        shell: pwsh
        run: |
          mkdir dist\installer 2>$null
          $iss = @'
#define MyAppName "MEXC Bot"
#define MyAppVersion "${{ github.run_number }}"
#define MyAppPublisher "Dali5599"
#define MyAppExeName "MEXC Bot.exe"

[Setup]
AppId={{A1F4B2F8-3D8A-4C6E-8B3D-FA2F3E8A7A01}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputDir=dist\installer
OutputBaseFilename=MEXC_Bot_Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesInstallIn64BitMode=x64
PrivilegesRequired=admin

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "arabic";  MessagesFile: "compiler:Languages\Arabic.isl"
Name: "french";  MessagesFile: "compiler:Languages\French.isl"

[Files]
Source: "dist\MEXC Bot\*"; DestDir: "{app}"; Flags: recursesubdirs ignoreversion

[Icons]
Name: "{group}\{#MyAppName}";        Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:"; Flags: unchecked

[Run]
Filename: "{app}\{#MyAppExeName}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{app}\logs"
Type: filesandordirs; Name: "{app}\data"
'@
          Set-Content -Path installer.iss -Value $iss -Encoding UTF8
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: MEXC_Bot_Installer
          path: dist/installer/MEXC_Bot_Setup.exe
